import { handleProxyRequest, type ProxyEnv } from "./proxy";
import { handleQueueBatch } from "./queue";

interface R2QueueMessage {
  action: string;
  bucket: string;
  object?: {
    key: string;
    size?: number;
    eTag?: string;
  };
  eventTime: string;
}

export interface Env extends ProxyEnv {
  // Add one [[r2_buckets]] block per bucket in wrangler.toml.
  // Example binding names are generated by scripts/generate_worker_config.py
  [key: string]: unknown;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return handleProxyRequest(request, env);
  },

  async queue(
    batch: MessageBatch<R2QueueMessage>,
    env: Env,
  ): Promise<void> {
    await handleQueueBatch(batch, env);
  },
} satisfies ExportedHandler<Env>;
